version: '3.4'

services:
  beststories.api:
    image: ${DOCKER_REGISTRY-}beststoriesapi
    environment:
        - ASPNETCORE_ENVIRONMENT=docker
        - ASPNETCORE_URLS=http://+:80
    ports:
        - 80:80
